services:
    caddy:
        image: "caddy:latest"
        restart: "always"
        environment:
            WIZDLE_WEB_PORT: "${WIZDLE_WEB_PORT}"
            WIZDLE_API_PORT: "${WIZDLE_API_PORT}"
        ports:
            - "443:443"
        volumes:
            - "./deploy/Caddyfile:/etc/caddy/Caddyfile:ro"
            - "/etc/caddy/certs:/etc/caddy/certs:ro"
        depends_on:
            - "wizdle-web"
            - "wizdle-api"
        networks:
            - "aspire"
