name: Publish Test Results
run-name: Publish Test Results
permissions:
    contents: read
    actions: read
    checks: write
    pull-requests: write
on:
    workflow_run:
        workflows: ["Build & Test"]
        types:
            - completed
jobs:
    publish_test_results:
        runs-on: ubuntu-latest
        steps:
            - uses: dorny/test-reporter@v3
              with:
                name: Publish Test Results
                artifact: /test-results-(.*)/
                path: '**/*.trx'
                reporter: dotnet-trx
                report-title: Wizdle Test Results
                fail-on-error: 'true'
                fail-on-empty: 'true'
                use-actions-summary: 'true'
